server:
  port: 9004

spring:
  application:
    name: user-config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:../user-config-repo
      fail-fast: true
