package com.dxu.sso.common.event.student;

public enum StudentDeleteReplyType {
    ENROLLMENTS_DELETED,
    ENROLLMENTS_DELETE_FAILED,
    ENROLLMENTS_RESTORED,
    ENROLLMENTS_RESTORE_FAILED,

    APPLICATIONS_DELETED,
    APPLICATIONS_DELETE_FAILED,
    APPLICATIONS_RESTORED,
    APPLICATIONS_RESTORE_FAILED
}
