server:
  port: 9014

spring:
  config:
    activate:
      on-profile: default

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-50623690.okta.com/oauth2/default

  datasource:
    url: jdbc:mysql://localhost:3306/ssocourseapp
    username: ssocourseapp
    password: passw0rd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Kafka producer
  kafka:
    bootstrap-servers: 172.27.223.47:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      retry-backoff-ms: 1000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost

# User APIs URLs in user-profile-svc and user-admin-svc
url:
  user:
    profile: http://localhost:9002/api/profile/me
    admin: http://localhost:9003/api/admin/users
  course:
    query: http://localhost:9012/api/courses
