server:
  port: 9763

spring:
  application:
    name: course-eureka-server
  config:
    import: configserver:http://localhost:9015

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9763/eureka/

  server:
    enable-self-preservation: false
    enable-replication: false
