server:
  port: 9001

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:9004

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-profile
          uri: lb://user-profile-svc
          predicates:
            - Path=/api/profile/**
          filters:
            - TokenRelay

        - id: user-admin
          uri: lb://user-admin-svc
          predicates:
            - Path=/api/admin/users/**
          filters:
            - TokenRelay

        - id: course-query
          uri: lb://course-query-svc
          predicates:
            - Path=/api/courses/**
          filters:
            - TokenRelay

        - id: course-management
          uri: lb://course-management-svc
          predicates:
            - Path=/api/manage/courses/**
          filters:
            - TokenRelay

        - id: course-registration
          uri: lb://course-registration-svc
          predicates:
            - Path=/api/registrations/**
          filters:
            - TokenRelay

  security:
    oauth2:
      client:
        registration:
          user-app:
            provider: okta
            client-id: 0oaooqy915xbkRCKT5d7
            client-secret: Ew-4IiHuFr6cgY1w3JhJ5PFWzvB-yZGx6xdD_y3rxhSWioOG-U_NGsCViCvlAxfe
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/user-app"
          course-app:
            provider: okta
            client-id: 0oaoor5c1wl5NU1ef5d7
            client-secret: AC-_PThmy1t69J7Q1Je2g4HNRXq1mPqAUGDspKsy6dTFGk7RVV00a5jKiwZVuJ3z
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/course-app"
        provider:
          okta:
            issuer-uri: https://dev-50623690.okta.com/oauth2/default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost

client:
  redirect-url:
    user-app: http://localhost:4200
    course-app: http://localhost:4201
