server:
  port: 9011

spring:
  application:
    name: course-gateway
  config:
    import: configserver:http://localhost:9015

  cloud:
    gateway:
      routes:
        - id: course-query
          uri: lb://course-query-svc
          predicates:
            - Path=/api/course-query/**
          filters:
            - TokenRelay

        - id: course-management
          uri: lb://course-management-svc
          predicates:
            - Path=/api/course-mgmt/**
          filters:
            - TokenRelay

        - id: course-registration
          uri: lb://course-registration-svc
          predicates:
            - Path=/api/course-registration/**
          filters:
            - TokenRelay

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaoor5c1wl5NU1ef5d7
            client-secret: AC-_PThmy1t69J7Q1Je2g4HNRXq1mPqAUGDspKsy6dTFGk7RVV00a5jKiwZVuJ3z
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/okta"
        provider:
          okta:
            issuer-uri: https://dev-50623690.okta.com/oauth2/default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9762/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost

angular:
  redirect_url: http://localhost:4200
