server:
  port: 9003

spring:
  config:
    activate:
      on-profile: default

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-50623690.okta.com/oauth2/default

  datasource:
    url: jdbc:mysql://localhost:3306/ssouser
    username: ssouser
    password: passw0rd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost

# User APIs URLs in user-profile-svc and user-admin-svc
url:
  user:
    profile: http://localhost:9002/api/profile/me
    admin: http://localhost:9003/api/users
