server:
  port: 9003

spring:
  config:
    activate:
      on-profile: default

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-50623690.okta.com/oauth2/default

  datasource:
    url: jdbc:mysql://localhost:3306/ssouser
    username: ssouser
    password: passw0rd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      # Prefer CHAR(36) instead of BINARY(16) for UUIDs
      hibernate.type.preferred_uuid_jdbc_type: CHAR

  # Kafka
  kafka:
    bootstrap-servers: 172.27.223.47:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      retry-backoff-ms: 1000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.dxu.sso.common.event.*"
    listener:
      missing-topics-fatal: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost

# User APIs URLs in user-profile-svc and user-admin-svc
url:
  user:
    profile: http://localhost:9002/api/profile/me
    admin: http://localhost:9003/api/admin/users
